### ISSUE TITLE
Sender/Receiver need to either be tied to a player, be created together, or Receivers should be created upon assigning a Sender. 

### ISSUE THREAD

**Issue by corylulu** [flokol120/Spigot-Item-Chest-Sorter#7] opened 2020-03-30 20:06 UTC
I figured out was an issue is the fact that the senders/receivers aren't linked to a player, which can result in two players making sender items one after another, then each make a receiver items and it results in both the receivers going to the second sender.

I was having weird issues like that. Perhaps it could also be solved by creating a receiver automatically after a sender hoe is used on a chest to ensure it correctly pairs. Would also allow for a bunch of them to be made by an OP, then people can just grab one and start using it without having to know any commands.

Another idea would be to always have a Receiver hoe present inside a Sender chest. 

Naming the sender/receiver pair might also help to stay organized if you want people to be able to create multiples.

**Comment by corylulu** [comment] 2020-03-30 20:10
Oh, just saw you already made a similar ticket. Is this already resolved?

**Comment by flokol120** [comment] 2020-03-30 20:10
possible duplicate of #6

**Comment by flokol120** [comment] 2020-03-30 20:11
Yes, this is fixed with 9022456735078c6326b68b36f8c75391453cdfb6

**Comment by corylulu** [comment] 2020-03-30 20:14
Need to investigate some more, but I've also been having issues with items that are supposed to be going to an Air chest just disappearing... 

Additionally, I think I was actually able to find the items again upon breaking either a sender or receiver chest, but I had reset the configuration file a couple times in between, so I'd need to verify if that was just a fluke.

**Comment by flokol120** [comment] 2020-04-02 12:48
@corylulu the issue with "disappearing" could be linked to the issue that another person mistakenly selected a receiver chest for your sender chest.
I have never witnessed that item disappeared. The part of item deletion is also pretty safe coded (imho). First a copy of the items are added to the receiver chest. If this part was successful the items are deleted from the sender chest. So the risk of items being duplicated is potentially higher than the risk of items disappearing.
I am closing this issue, as it is possibly resolved.

**Closed by flokol120** 2020-04-02 12:48 UTC
Labels: bug
