### ISSUE TITLE
[REQUEST]

### ISSUE THREAD

**Issue by delimedia** [flokol120/Spigot-Item-Chest-Sorter#54] opened 2023-10-23 14:18 UTC
Would it be possible to add more Sender chests to the existing network?
I have tried to create two sender-chests but I get the message that there is no receiver-chest in the second chest.

Or am I making a mistake?

**Comment by flokol120** [comment] 2023-10-23 14:41
Implementing this is very hard as per definition, only one sender is associated with an array of receivers. However, there are two ways to circumvent this restriction:

1. Add a new sender and manually add all desired receivers (only viable for a few receivers)
2. Set `sendFromHopperOrSender` to true within the config.yml. This way, you can define a new sender, which has only one receiver: Your other sender chest. The initial sender will forward any items passed onto it by other senders. Keep in mind, that this setting should only be activated on private servers, as it is possible to create loops of senders/receivers, which will crash the server!

This issue is a duplicate of #12. (Though, I admit I did not line out any solutions for the issue)

You are welcome to reopen the issue, if my solutions do not fit your use case.

**Closed by flokol120** 2023-10-23 14:41 UTC
Labels: enhancement, help wanted
